version: "3.8"
services:
  db:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    volumes:
      - datadb:/var/lib/mysql

  pma:
    image: phpmyadmin
    container_name: pma
    environment:
      - PMA_ARBITARY=1
      - PMA_PORT=80
    ports:
      - '5050:80'
    depends_on:
      - db

  frontend:
    build: ./restaurant-app
    container_name: frontend
    ports:
      - '8080:8080'
    volumes:
      - ./restaurant-app/src:/app/src

  backend:
      build: ./restaurant-backend
      container_name: backend
      restart: always
      ports:
      - '5000:5000'
      depends_on:
      - db

volumes:
  datadb:
  backend_data:
