version: "3.8"
services:
  db:
    image: mysql:latest
    container_name: mysql-restapp
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - datadb:/var/lib/mysql

  pma:
    image: phpmyadmin
    container_name: pma-restapp
    environment:
      - PMA_ARBITARY=1
      - PMA_PORT=80
    ports:
      - '5050:80'
    depends_on:
      - db

  frontend:
    build: ./restaurant-app
    container_name: frontend-restapp
    ports:
      - '8080:8080'
    stdin_open: true
    tty: true
    volumes:
      - ./restaurant-app/src:/app/src

  backend:
      build: ./restaurant-backend
      container_name: backend-restapp
      restart: always
      ports:
      - '5000:5000'
      depends_on:
      - db

volumes:
  datadb:
  backend_data:
