"""empty message

Revision ID: 4536b6820a75
Revises: 
Create Date: 2023-12-18 08:42:08.632421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4536b6820a75'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_and_beverage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('food_and_beverage', schema=None) as batch_op:
        batch_op.drop_column('path')

    # ### end Alembic commands ###
